#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests before commit..."
npm test

if [ $? -ne 0 ]; then
  echo "Tests failed, aborting commit."
  exit 1
fi

echo "Tests passed, proceeding with commit."
